### ISSUE TITLE
Issue with discord bot

### ISSUE THREAD

**Issue by remembermeads** [shuttleai/shuttleai-discord#1]
Hey!

I know that the people that self-host the bot do not receive support but this is a heavy issue related to the bot which could affect people hosting the bot.

Number 1 issue, when generating an image I get the error -

`04:54:38 ERR > An error occurred: 'AutoShardedBot' object has no attribute 'entitlements'. This is when imagine is ran and with any prompt and model.`

Number 2 issue, when generating an image by my friends the 2nd time they generate they get this error - 

`An error occurred: Session is closed
An error occurred: a bytes-like object is required, not 'str'`

![image](https://github.com/shuttleai/shuttleai-discord/assets/162580284/8a8151c9-eebd-4d19-84e5-e6d772c5d8a9)
![image](https://github.com/shuttleai/shuttleai-discord/assets/162580284/ada58dbf-4ea8-4b11-b6d9-19b33f2beeb5)
![image](https://github.com/shuttleai/shuttleai-discord/assets/162580284/a2932dda-e92e-46ca-8972-f610563d4cf8)

Thanks!

**Comment by tristandevs** [comment]
Download the latest version of discord.py from https://github.com/Rapptz/discord.py and the downloaded beta version, or remove entitlements from the code, and session issue will be fixed soon

**Comment by tristandevs** [comment]
I have fixed the session error in the latest commit
